CREATE TABLE polaris.default.eco_events_dist (
  eventTimeMs TIMESTAMP NOT NULL,
  customerId INT NOT NULL,
  clientId STRING NOT NULL,
  appInstanceId STRING,
  sessionId STRING,
  sessionStartMs TIMESTAMP,
  inSession BOOLEAN,
  userSessionId LONG,
  inUserSession BOOLEAN,
  platform STRING,
  platformSubcategory STRING,
  appName STRING,
  appBuild STRING,
  appVersion STRING,
  sensorVersion STRING,
  referrerHost STRING,
  host STRING,
  path STRING,
  query STRING,
  referrer STRING,
  title STRING,
  url STRING,
  deviceName STRING,
  deviceCategory STRING,
  deviceHardwareType STRING,
  deviceManufacturer STRING,
  deviceMarketingName STRING,
  deviceOperatingSystem STRING,
  deviceOperatingSystemVersion STRING,
  deviceOperatingSystemFamily STRING,
  deviceModel STRING,
  deviceVendor STRING,
  browserName STRING,
  browserVersion STRING,
  playerFrameworkName STRING,
  playerFrameworkVersion STRING,
  country LONG,
  state LONG,
  city LONG,
  countryIso STRING,
  sub1Iso STRING,
  sub2Iso STRING,
  cityGid INT,
  dma SMALLINT,
  postalCode STRING,
  timezoneOffsetMins INT,
  ipV4 STRING,
  ipV6 STRING,
  userId STRING,
  asn INT,
  isp INT,
  domain STRING,
  connType INT,
  netSpeed STRING,
  eventVendor STRING,
  eventVersion STRING,
  eventCategory STRING,
  eventName STRING,
  networkRequestDurationMs DOUBLE,
  watermarkMs TIMESTAMP,
  partitionId INT,
  tagGroup1  MAP<STRING, STRING>,
  tagGroup2  MAP<STRING, STRING>,
  tagGroup3  MAP<STRING, STRING>,
  tagGroup4  MAP<STRING, STRING>,
  tagGroup5  MAP<STRING, STRING>,
  tagGroup6  MAP<STRING, STRING>,
  tagGroup7  MAP<STRING, STRING>,
  tagGroup8  MAP<STRING, STRING>,
  tagGroup9  MAP<STRING, STRING>,
  tagGroup10 MAP<STRING, STRING>,
  tagGroup11 MAP<STRING, STRING>,
  tagGroup12 MAP<STRING, STRING>,
  tagGroup13 MAP<STRING, STRING>,
  tagGroup14 MAP<STRING, STRING>,
  tagGroup15 MAP<STRING, STRING>,
  customStrFloat32MapGroup1 MAP<STRING, DOUBLE>,
  customStrInt32MapGroup1   MAP<STRING, INT>,
  metricIntGroup1  MAP<STRING, LONG>,
  metricIntGroup2  MAP<STRING, LONG>,
  metricIntGroup3  MAP<STRING, LONG>,
  metricIntGroup4  MAP<STRING, LONG>,
  metricIntGroup5  MAP<STRING, LONG>,
  metricIntGroup6  MAP<STRING, LONG>,
  metricIntGroup7  MAP<STRING, LONG>,
  metricIntGroup8  MAP<STRING, LONG>,
  metricIntGroup9  MAP<STRING, LONG>,
  metricIntGroup10 MAP<STRING, LONG>,
  metricIntGroup11 MAP<STRING, LONG>,
  metricIntGroup12 MAP<STRING, LONG>,
  metricIntGroup13 MAP<STRING, LONG>,
  metricIntGroup14 MAP<STRING, LONG>,
  metricIntGroup15 MAP<STRING, LONG>,
  metricFloatGroup1  MAP<STRING, DOUBLE>,
  metricFloatGroup2  MAP<STRING, DOUBLE>,
  metricFloatGroup3  MAP<STRING, DOUBLE>,
  metricFloatGroup4  MAP<STRING, DOUBLE>,
  metricFloatGroup5  MAP<STRING, DOUBLE>,
  metricFloatGroup6  MAP<STRING, DOUBLE>,
  metricFloatGroup7  MAP<STRING, DOUBLE>,
  metricFloatGroup8  MAP<STRING, DOUBLE>,
  metricFloatGroup9  MAP<STRING, DOUBLE>,
  metricFloatGroup10 MAP<STRING, DOUBLE>,
  metricFloatGroup11 MAP<STRING, DOUBLE>,
  metricFloatGroup12 MAP<STRING, DOUBLE>,
  metricFloatGroup13 MAP<STRING, DOUBLE>,
  metricFloatGroup14 MAP<STRING, DOUBLE>,
  metricFloatGroup15 MAP<STRING, DOUBLE>
)
USING iceberg
PARTITIONED BY (
  customerId,
  days(eventTimeMs)
)
TBLPROPERTIES (
  'format-version' = '2',
  'write.format.default' = 'parquet',
  'write.distribution-mode' = 'hash',
  'write.object-storage.enabled' = 'true',
  'write.object-storage.partitioned-paths' = 'true',
  'write.parquet.compression-codec' = 'zstd',
  'write.target-file-size-bytes' = '536870912'
);
