CREATE TABLE polaris.default.eco_event_summary_pt1m_dist (
  timestampMs TIMESTAMP NOT NULL,
  eventName STRING,
  eventCategory STRING,
  customerId INT NOT NULL,
  clientId STRING NOT NULL,
  sessionId STRING,
  inSession BOOLEAN,
  userSessionId LONG,
  inUserSession BOOLEAN,
  platform STRING,
  platformSubcategory STRING,
  appName STRING,
  appBuild STRING,
  appVersion STRING,
  browserName STRING,
  browserVersion STRING,
  userId STRING,
  deviceManufacturer STRING,
  deviceMarketingName STRING,
  deviceModel STRING,
  deviceHardwareType STRING,
  deviceName STRING,
  deviceCategory STRING,
  deviceOperatingSystem STRING,
  deviceOperatingSystemVersion STRING,
  deviceOperatingSystemFamily STRING,
  country LONG,
  state LONG,
  city LONG,
  countryIso STRING,
  sub1Iso STRING,
  sub2Iso STRING,
  cityGid INT,
  dma SMALLINT,
  postalCode STRING,
  isp INT,
  netSpeed STRING,
  sensorVersion STRING,
  appType STRING,
  asn INT,
  timezoneOffsetMins INT,
  connType INT,
  host STRING,
  path STRING,
  referrer STRING,
  title STRING,
  referrerHost STRING,
  impactedFlow STRING,
  flowTagIntGroup1   MAP<STRING, LONG>,
  flowTagFloatGroup1 MAP<STRING, DOUBLE>,
  watermarkMs TIMESTAMP,
  partitionId INT,
  retentionDate DATE,
  tagGroup1  MAP<STRING, STRING>,
  tagGroup2  MAP<STRING, STRING>,
  tagGroup3  MAP<STRING, STRING>,
  tagGroup4  MAP<STRING, STRING>,
  tagGroup5  MAP<STRING, STRING>,
  tagGroup6  MAP<STRING, STRING>,
  tagGroup7  MAP<STRING, STRING>,
  tagGroup8  MAP<STRING, STRING>,
  tagGroup9  MAP<STRING, STRING>,
  tagGroup10 MAP<STRING, STRING>,
  tagGroup11 MAP<STRING, STRING>,
  tagGroup12 MAP<STRING, STRING>,
  tagGroup13 MAP<STRING, STRING>,
  tagGroup14 MAP<STRING, STRING>,
  tagGroup15 MAP<STRING, STRING>,
  metricIntGroup1   MAP<STRING, LONG>,
  metricIntGroup2   MAP<STRING, LONG>,
  metricIntGroup3   MAP<STRING, LONG>,
  metricIntGroup4   MAP<STRING, LONG>,
  metricIntGroup5   MAP<STRING, LONG>,
  metricIntGroup6   MAP<STRING, LONG>,
  metricIntGroup7   MAP<STRING, LONG>,
  metricIntGroup8   MAP<STRING, LONG>,
  metricIntGroup9   MAP<STRING, LONG>,
  metricIntGroup10  MAP<STRING, LONG>,
  metricIntGroup11  MAP<STRING, LONG>,
  metricIntGroup12  MAP<STRING, LONG>,
  metricIntGroup13  MAP<STRING, LONG>,
  metricIntGroup14  MAP<STRING, LONG>,
  metricIntGroup15  MAP<STRING, LONG>,
  metricFloatGroup1   MAP<STRING, DOUBLE>,
  metricFloatGroup2   MAP<STRING, DOUBLE>,
  metricFloatGroup3   MAP<STRING, DOUBLE>,
  metricFloatGroup4   MAP<STRING, DOUBLE>,
  metricFloatGroup5   MAP<STRING, DOUBLE>,
  metricFloatGroup6   MAP<STRING, DOUBLE>,
  metricFloatGroup7   MAP<STRING, DOUBLE>,
  metricFloatGroup8   MAP<STRING, DOUBLE>,
  metricFloatGroup9   MAP<STRING, DOUBLE>,
  metricFloatGroup10  MAP<STRING, DOUBLE>,
  metricFloatGroup11  MAP<STRING, DOUBLE>,
  metricFloatGroup12  MAP<STRING, DOUBLE>,
  metricFloatGroup13  MAP<STRING, DOUBLE>,
  metricFloatGroup14  MAP<STRING, DOUBLE>,
  metricFloatGroup15  MAP<STRING, DOUBLE>
)
USING iceberg
PARTITIONED BY (
  customerId,
  days(timestampMs)
)
TBLPROPERTIES (
  'format-version' = '2',
  'write.format.default'='parquet',
  'write.distribution-mode' = 'hash',
  'write.object-storage.enabled'='true',
  'write.object-storage.partitioned-paths'='true',
  'write.parquet.compression-codec'='zstd',
  'write.target-file-size-bytes' = '536870912'
);
